#!/bin/bash

#check if Timer is already disabled
Timer_enable=$(cat /data/log/Timer_enable)
if [$Timer_enable != 0] then
	# disable Timer
	echo "0" >| /data/log/Timer_enable
	# log event
	VMFB_logfile="/data/log/VMFB_$(date +%F).log"
	touch "$VMFB_logfile"
	echo "$(date +%F_%X)	TMR	OFF">> "$VMFB_logfile"
fi