#!/bin/bash

# Assign pins
TMR=16 #RPi ZeroW Pin #36

#Toggle the TMR enable pin
Timer_enable=$(cat /sys/class/gpio/gpio$TMR/value)
if [ $Timer_enable == "1" ] 
then
	# disable Timer
	echo "0" >| /sys/class/gpio/gpio$TMR/value
else
	# enable Timer
	echo "1" >| /sys/class/gpio/gpio$TMR/value
fi
