#!/bin/bash

#check if Timer is already enabled
Timer_enable=$(cat /data/log/Timer_enable)
if [$Timer_enable != 1] then
	# enable Timer
	echo "1" >| /data/log/Timer_enable
	# log event
	VMFB_logfile="/data/log/VMFB_$(date +%F).log"
	touch "$VMFB_logfile"
	echo "$(date +%F_%X)	TMR	ON">> "$VMFB_logfile"
fi