#!/bin/bash

# Assign pins
MTR=11
 
# Verify they are set up, else initialize them
test -e /sys/class/gpio/gpio$MTR ||
  (echo $MTR > /sys/class/gpio/export \
   && echo out > /sys/class/gpio/gpio$MTR/direction)

# Set the pin to high, wait 1s, then set it back to low
echo "1">/sys/class/gpio/gpio$MTR/value
