#!/bin/bash

# Assign pins
SIRCON=25 
DISCON=11

# Set pins 11 and 25 to be outputs driving low to avoid them going high on start up.
# Add the following line to your /boot/config.txt
# gpio=11,25=op,dl
 
# Verify they are set up, else initialize them
test -e /sys/class/gpio/gpio$SIRCON ||
  (echo $SIRCON > /sys/class/gpio/export \
   && echo out > /sys/class/gpio/gpio$SIRCON/direction)
test -e /sys/class/gpio/gpio$DISCON ||
  (echo $DISCON > /sys/class/gpio/export \
   && echo out > /sys/class/gpio/gpio$DISCON/direction)

# Set the pin to high, wait 1s, then set it back to low
echo "1">/sys/class/gpio/gpio$SIRCON/value
echo "1">/sys/class/gpio/gpio$DISCON/value
sleep 1
echo "0">/sys/class/gpio/gpio$SIRCON/value
echo "0">/sys/class/gpio/gpio$DISCON/value

