#!/bin/bash

# swap the camera config file and restart motion and the motioneye server
cp /data/etc/camera-1.conf.disable_camera /data/etc/camera-1.conf
cp /data/etc/motion.conf.disable_camera /data/etc/motion.conf
meyectl stopserver -b -c motioneye.conf
meyectl startserver -b -c motioneye.conf

