#!/bin/bash

#check if PBKA is already disabled
PBKA_enable=$(cat /data/log/PBKA_enable)
if [$PBKA_enable != 0] then
	# disable PBKA
	echo "0" >| /data/log/PBKA_enable
	# log event
	VMFB_logfile="/data/log/VMFB_$(date +%F).log"
	touch "$VMFB_logfile"
	echo "$(date +%F_%X)	PBKA	OFF">> "$VMFB_logfile"
fi