#!/bin/bash

#check if PBKA is already enabled
PBKA_enable=$(cat /data/log/PBKA_enable)
if [$PBKA_enable != 1] then
	# disable PBKA
	echo "1" >| /data/log/PBKA_enable
	# log event
	VMFB_logfile="/data/log/VMFB_$(date +%F).log"
	touch "$VMFB_logfile"
	echo "$(date +%F_%X)	PBKA	ON">> "$VMFB_logfile"
fi