#!/bin/bash

# Set up input pins and check their values
# Assign pins
PIR=27 #RPi ZeroW Pin #13
SIR=25 #RPi ZeroW Pin #22
MTR=11 #RPi ZeroW Pin #23
MT=5 #RPi ZeroW Pin #29
DEP=24 #RPi ZeroW Pin #18
DIS=10 #RPi ZeroW Pin #19
PBKA=19 #RPi ZeroW Pin #35
TMR=13 #RPi ZeroW Pin #33

# Get the current pin values
valPIR=$(cat /sys/class/gpio/gpio$PIR/value)
valSIR=$(cat /sys/class/gpio/gpio$SIR/value)
valMTR=$(cat /sys/class/gpio/gpio$MTR/value)
valMT=$(cat /sys/class/gpio/gpio$MT/value)
valDEP=$(cat /sys/class/gpio/gpio$DEP/value)
valDIS=$(cat /sys/class/gpio/gpio$DIS/value)
valPBKA=$(cat /sys/class/gpio/gpio$PBKA/value)
valTMR=$(cat /sys/class/gpio/gpio$TMR/value)

# Set the display text for the pin values 

if [ "$valPIR" == "1" ]
then
    PIR_text="<font color=#FF0000>PIR</font>"
else
    PIR_text="PIR"
fi
 
if [ "$valSIR" == "1" ]
then
    SIR_text="<font color=#FF0000>SIR</font>"
else
    SIR_text="SIR"
fi

if [ "$valMTR" == "1" ]
then
    MTR_text="<font color="#FF0000">MTR</font>"
else
    MTR_text="MTR"
fi

# Deposit and Dispense events are too short to catch unless there is a jam
if [ "$valDIS" == "1" ]
then
    DIS_text="<font color=#FF0000>DIS</font>"
else
    DIS_text="DIS"
fi

if [ "$valDEP" == "1" ]
then
    DEP_text="<font color=#FF0000>DEP</font>"
else
    DEP_text="DEP"
fi

if [ "$valMT" == "1" ]
then
    MT_text=""
else
    MT_text="&#129372;"
fi

if [ "$valTMR" == "1" ] 
then
	TMR_text="&#9202;"
else
	TMR_text=""
fi

if [ "$valPBKA" == "1" ] 
then
	PBKA_text="&#128498;"
else
	PBKA_text=""
fi

VMFB_logfile="/data/log/VMFB_$(date +%F).log"
touch "$VMFB_logfile"
PIRcount=$(grep -c 'PIR[[:blank:]]1' $VMFB_logfile)
DEPcount=$(grep -c 'DEP[[:blank:]]1' $VMFB_logfile)
DIScount=$(grep -c 'DIS[[:blank:]]1' $VMFB_logfile)
MANcount=$(grep -c 'MAN[[:blank:]]DISPENSE' $VMFB_logfile)
TMRcount=$(grep -c 'TMR[[:blank:]]DISPENSE' $VMFB_logfile)

# Output to the UI
echo "$PBKA_text$TMR_text$MT_text|$PIR_text<sup>$PIRcount</sup>|$DEP_text<sup>$DEPcount</sup>|$DIS_text<sup>$DIScount</sup>|TMR<sup>$TMRcount</sup>|MAN<sup>$MANcount</sup>|$SIR_text|$MTR_text"
# 1 second delay between executions
echo 1 1>&2

