#!/bin/bash

# Set up input pins and check their values
# Assign pins
PIR=27 #RPi ZeroW Pin #13
SIR=25 #RPi ZeroW Pin #22
MTR=11 #RPi ZeroW Pin #23
MT=5 #RPi ZeroW Pin #29
DEP=24 #RPi ZeroW Pin #18
DIS=10 #RPi ZeroW Pin #19
PBKA=19 #RPi ZeroW Pin #35
TMR=13 #RPi ZeroW Pin #33

# Get the values for the last script execution
prev_valEMT=$(cat /data/log/prev_valEMT)

# Get the current pin values
valPIR=$(cat /sys/class/gpio/gpio$PIR/value)
valSIR=$(cat /sys/class/gpio/gpio$SIR/value)
valMTR=$(cat /sys/class/gpio/gpio$MTR/value)
valMT=$(cat /sys/class/gpio/gpio$MT/value)
valDEP=$(cat /sys/class/gpio/gpio$DEP/value)
valDIS=$(cat /sys/class/gpio/gpio$DIS/value)
valPBKA=$(cat /sys/class/gpio/gpio$PBKA/value)
valTMR=$(cat /sys/class/gpio/gpio$TMR/value)

# Set the display text for the pin values 

if [ "$valPIR" == "1" ]
then
    PIR_text="+"
else
    PIR_text="-"
fi
 
if [ "$valSIR" == "1" ]
then
    SIR_text="+"
else
    SIR_text="-"
fi

if [ "$valMTR" == "1" ]
then
    MTR_text="+"
else
    MTR_text="-"
fi

# Deposit and Dispense events are too short to catch unless there is a jam
if [ "$valDIS" == "1" ]
then
    DIS_text="+"
else
    DIS_text="-"
fi

if [ "$valDEP" == "1" ]
then
    DEP_text="+"
else
    DEP_text="-"
fi

if [ "$valEMT" == "1" ]
then
    EMT_text=""
else
    EMT_text="&#129372;"
fi

if [ "$valTMR" == "1" ] 
then
	TMR_text="&#9202;"
else
	TMR_text=""
fi

if [ "$valPBKA" == "1" ] 
then
	PBKA_text="&#128498;"
else
	PBKA_text=""
fi

VMFB_logfile="/data/log/VMFB_$(date +%F).log"
touch "$VMFB_logfile"
PIRcount=$(grep -c 'PIR\t\+' $VMFB_logfile)
DEPcount=$(grep -c 'DEP\t\+' $VMFB_logfile)
DIScount=$(grep -c 'DIS\t\+' $VMFB_logfile)

# Output to the UI
echo "$PBKA_text$TMR_text$EMT_text|PIR$PIR_text$PIRcount|DEP$DEP_text$DEPcount|DIS$DIS_text$DIScount|IR$SIR_text|MTR$MTR_text"
# 1 second delay between executions
echo 1 1>&2

