#!/bin/bash

# Assign pins
CAL=23 #RPi ZeroW Pin #16

#Toggle the PBKA enable pin
CAL_enable=$(cat /sys/class/gpio/gpio$CAL/value)
if [ $CAL_enable == "1" ] 
then
	# disable calibration mode
	echo "0" >| /sys/class/gpio/gpio$CAL/value
else
	# enable calibration mode
	echo "1" >| /sys/class/gpio/gpio$CAL/value
fi
